apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world 
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: containersol/hello-world
        ports:
        - containerPort: 80
